service: better-sqlite3-lambda-layer
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  logRetentionInDays: 14

package:
  exclude:
    - node_modules/**
    - build/**
  
  
functions:
  example:
    handler: example/handler.hello
    layers: 
      - {Ref: BetterSqlite3LambdaLayer}
    

layers:
  BetterSqlite3:
    path: layer
    description: A Layer to provide fast SQLite support in node.js Lambda functions using better-sqlite3
    compatibleRuntimes:
      - nodejs8.10
